// <auto-generated />
using DishAPI.Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DishAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241028035635_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TEST1")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DishAPI.Application.Models.Category", b =>
                {
                    b.Property<decimal>("LoaiMonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LOAIMONANID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("LoaiMonAnId"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("LoaiMonAnId")
                        .HasName("SYS_C007786");

                    b.ToTable("CATEGORIES", "TEST1");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.Property<decimal>("MonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MONANID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("MonAnId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("GHICHU");

                    b.Property<decimal?>("LoaiMonAnId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LOAIMONANID");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENMON");

                    b.HasKey("MonAnId")
                        .HasName("SYS_C007790");

                    b.HasIndex("LoaiMonAnId");

                    b.ToTable("DISHES", "TEST1");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Ingredient", b =>
                {
                    b.Property<decimal>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NGUYENLIEUID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("NguyenLieuId"));

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENNGUYENLIEU");

                    b.HasKey("NguyenLieuId")
                        .HasName("SYS_C007788");

                    b.ToTable("INGREDIENTS", "TEST1");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Recipe", b =>
                {
                    b.Property<decimal>("CongThucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CONGTHUCID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CongThucId"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("DONVITINH");

                    b.Property<decimal>("MonAnId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MONANID");

                    b.Property<decimal>("NguyenLieuId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NGUYENLIEUID");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SOLUONG");

                    b.HasKey("CongThucId")
                        .HasName("SYS_C007793");

                    b.HasIndex("MonAnId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("RECIPES", "TEST1");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.HasOne("DishAPI.Application.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("LoaiMonAnId")
                        .HasConstraintName("SYS_C007791");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Recipe", b =>
                {
                    b.HasOne("DishAPI.Application.Models.Dish", "Dish")
                        .WithMany("Recipes")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("SYS_C007794");

                    b.HasOne("DishAPI.Application.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("SYS_C007795");

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
