// <auto-generated />
using DishAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DishAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DishAPI.Application.Models.Category", b =>
                {
                    b.Property<int>("LoaiMonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMonAnId"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LoaiMonAnId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.Property<int>("MonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("LoaiMonAnId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MonAnId");

                    b.HasIndex("LoaiMonAnId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Ingredient", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"));

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("NguyenLieuId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Recipe", b =>
                {
                    b.Property<int>("CongThucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongThucId"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MonAnId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CongThucId");

                    b.HasIndex("MonAnId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.HasOne("DishAPI.Application.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("LoaiMonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Recipe", b =>
                {
                    b.HasOne("DishAPI.Application.Models.Dish", "Dish")
                        .WithMany("Recipes")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DishAPI.Application.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Dish", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DishAPI.Application.Models.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
